notifications:
  email: false
git:
  quiet: true
  depth: false
jdk: openjdk11
node_js: lts/*
python: 3.7
matrix:
  include:
  - python: 3.7
addons:
  apt:
    update: true
    packages:
    - python3-pip
    #- curl
    - jq
install: true
before_install:
- |
  if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
    mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
    curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
  fi
  source ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
- stop_any 8080
#
- pip -V
- export PATH=$HOME/.local/bin:$PATH
- pip install --user --upgrade pip
- pip install --user --upgrade httpie
- http --version --debug
- pip -V
jobs:
  include:
  - stage: test
    jdk: openjdk11
    name: mvn test
    script:
    - cd $TRAVIS_BUILD_DIR && ./gradlew
    - bash $TRAVIS_BUILD_DIR/build/libs/*.jar &
    - wait_for 8080
    - curl -X POST localhost:8080 -d body=ololo -i
    - http :8080
    - curl -X POST localhost:8080 -d body=trololo -v
    - http :8080/
    - curl localhost:8080/history
    #- http --stream :8080/history
    - http :8080/
    - stop_any 80 8080
cache:
  npm: true
  pip: true
  packages: true
  directories:
  - ~/.m2
  - ~/.local/daggerok
